import{createMinutes,toMarkdown}from'./lib/minutes.js';import{downloadInfographic}from'./lib/infographic.js';
const $=s=>document.querySelector(s),name=$('#name'),text=$('#transcript'),result=$('#result'),status=$('#status'),dot=$('#dot'),file=$('#file');let minutes;
const sample='文化祭の受付方法について話し合いました。参加者は入口でQRコードを読み取ります。受付担当は2名にすることに決定しました。吉本さんが金曜日までに案内画像を作成します。次回は月曜日に動作確認を行います。';
const esc=s=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const block=(title,xs)=>`<div class="block"><h4>${title}</h4>${xs.length?`<ul>${xs.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`:'<p class="muted">該当なし（必要に応じて編集してください）</p>'}</div>`;
function render(){if(!text.value.trim()){result.innerHTML='<div class="empty"><div>✦</div><p>文字起こしが入ると<br/>ここに議事録が表示されます</p></div>';return}minutes=createMinutes(text.value,name.value||'会議まとめ');result.innerHTML=`<h3>${esc(minutes.title)}</h3>${block('要約',minutes.summary)}${block('決定事項',minutes.decisions)}${block('次にやること',minutes.actions)}<div class="tags">${minutes.keywords.map(k=>`<span>#${esc(k)}</span>`).join('')}</div><div class="actions"><button id="save">議事録を保存</button><button class="primary" id="image">カラフル図解を保存</button></div>`;$('#save').onclick=save;$('#image').onclick=()=>downloadInfographic(minutes)}
function save(){const blob=new Blob([toMarkdown(minutes,text.value)],{type:'text/markdown;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`${minutes.title}-議事録.md`;a.click();URL.revokeObjectURL(a.href)}
async function decode(f){const context=new AudioContext({sampleRate:16000});try{const decoded=await context.decodeAudioData(await f.arrayBuffer()),offline=new OfflineAudioContext(1,Math.ceil(decoded.duration*16000),16000),source=offline.createBufferSource();source.buffer=decoded;source.connect(offline.destination);source.start();return(await offline.startRendering()).getChannelData(0).slice()}finally{await context.close()}}
async function transcribe(audio){status.textContent='初回のみ、文字起こしAIを読み込んでいます…';const{pipeline,env}=await import('https://cdn.jsdelivr.net/npm/@huggingface/transformers@3.7.2');env.allowLocalModels=false;const worker=await pipeline('automatic-speech-recognition','onnx-community/whisper-tiny',{dtype:'q8',progress_callback:p=>{if(p?.progress)status.textContent=`AIを準備中 ${Math.round(p.progress)}%`}});status.textContent='文字起こし中…（長い録画は時間がかかります）';const out=await worker(audio,{language:'japanese',task:'transcribe',chunk_length_s:30,stride_length_s:5});return String(Array.isArray(out)?out[0]?.text:out?.text??'').trim()}
file.onchange=async()=>{if(!file.files[0])return;file.disabled=true;dot.classList.add('pulse');try{status.textContent='音声を準備中…';text.value=await transcribe(await decode(file.files[0]));status.textContent='完成しました';render()}catch(e){console.error(e);status.textContent='処理できませんでした。MP3・M4A・WAVを試すか、文字起こしを貼り付けてください。'}finally{file.disabled=false;dot.classList.remove('pulse')}};text.oninput=render;name.oninput=render;$('#sample').onclick=()=>{text.value=sample;render()};
