import{createMinutes,toMarkdown}from'./lib/minutes.js';
import{downloadInfographic}from'./lib/infographic.js';
import{cloudConfigured,initCloud,getSession,onAuthChange,sendMagicLink,signOut,syncLocalMeetings,saveCloudMeeting,listCloudMeetings,createTicket,replyToTicket,listTickets}from'./cloud.js';

const $=s=>document.querySelector(s),name=$('#name'),text=$('#transcript'),result=$('#result'),status=$('#status'),dot=$('#dot'),file=$('#file');
const LOCAL_KEY='meeting-canvas-history-v1';
const sample='文化祭の受付方法について話し合いました。参加者は入口でQRコードを読み取ります。受付担当は2名にすることに決定しました。吉本さんが金曜日までに案内画像を作成します。次回は月曜日に動作確認を行います。';
let minutes=null,session=null,history=[],ticketTimer=null;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const block=(title,xs)=>`<div class="block"><h4>${title}</h4>${xs.length?`<ul>${xs.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`:'<p class="muted">該当なし（必要に応じて編集してください）</p>'}</div>`;

function render(){if(!text.value.trim()){minutes=null;result.innerHTML='<div class="empty"><div>✦</div><p>文字起こしが入ると<br/>ここに議事録が表示されます</p></div>';return}minutes=createMinutes(text.value,name.value||'会議まとめ');result.innerHTML=`<h3>${esc(minutes.title)}</h3>${block('要約',minutes.summary)}${block('決定事項',minutes.decisions)}${block('次にやること',minutes.actions)}<div class="tags">${minutes.keywords.map(k=>`<span>#${esc(k)}</span>`).join('')}</div><div class="actions"><button id="save">議事録を保存</button><button id="history-action">履歴に保存</button><button class="primary" id="image">カラフル図解を保存</button></div>`;$('#save').onclick=saveMarkdown;$('#history-action').onclick=saveCurrentHistory;$('#image').onclick=()=>downloadInfographic(minutes)}
function saveMarkdown(){const blob=new Blob([toMarkdown(minutes,text.value)],{type:'text/markdown;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`${minutes.title}-議事録.md`;a.click();URL.revokeObjectURL(a.href)}
async function decode(f){const context=new AudioContext({sampleRate:16000});try{const decoded=await context.decodeAudioData(await f.arrayBuffer()),offline=new OfflineAudioContext(1,Math.ceil(decoded.duration*16000),16000),source=offline.createBufferSource();source.buffer=decoded;source.connect(offline.destination);source.start();return(await offline.startRendering()).getChannelData(0).slice()}finally{await context.close()}}
async function transcribe(audio){status.textContent='初回のみ、文字起こしAIを読み込んでいます…';const{pipeline,env}=await import('https://cdn.jsdelivr.net/npm/@huggingface/transformers@3.7.2');env.allowLocalModels=false;const worker=await pipeline('automatic-speech-recognition','onnx-community/whisper-tiny',{dtype:'q8',progress_callback:p=>{if(p?.progress)status.textContent=`AIを準備中 ${Math.round(p.progress)}%`}});status.textContent='文字起こし中…（長い録画は時間がかかります）';const out=await worker(audio,{language:'japanese',task:'transcribe',chunk_length_s:30,stride_length_s:5});return String(Array.isArray(out)?out[0]?.text:out?.text??'').trim()}

function localHistory(){try{return JSON.parse(localStorage.getItem(LOCAL_KEY)||'[]')}catch{return[]}}
function writeLocal(items){localStorage.setItem(LOCAL_KEY,JSON.stringify(items.slice(0,50)))}
function mergeHistory(a,b){const map=new Map;[...a,...b].forEach(r=>{if(!map.has(r.id))map.set(r.id,r)});return[...map.values()].sort((x,y)=>new Date(y.created_at)-new Date(x.created_at))}
function renderHistory(){const box=$('#history-list');if(!history.length){box.innerHTML='<div class="feature-empty">保存した会議はまだありません</div>';return}box.innerHTML=history.map(r=>`<article class="history-item" data-id="${esc(r.id)}"><div><time>${new Date(r.created_at).toLocaleString('ja-JP')}</time><h3>${esc(r.title)}</h3><p>${esc(r.minutes?.summary?.[0]||r.transcript.slice(0,80)||'')}</p></div><button class="history-open">開く</button></article>`).join('');box.querySelectorAll('.history-item').forEach(el=>el.querySelector('button').onclick=()=>openHistory(el.dataset.id))}
function openHistory(id){const item=history.find(r=>r.id===id);if(!item)return;name.value=item.title;text.value=item.transcript;render();document.querySelector('.workspace').scrollIntoView({behavior:'smooth'})}
async function saveCurrentHistory(){if(!minutes){showToast('先に会議内容を入力してください');return}const record={id:crypto.randomUUID(),title:minutes.title,transcript:text.value,minutes,created_at:new Date().toISOString()};history=mergeHistory([record],history);writeLocal(mergeHistory([record],localHistory()));renderHistory();try{if(session)await saveCloudMeeting(record);showToast(session?'履歴を保存・同期しました':'この端末に履歴を保存しました')}catch(e){console.error(e);showToast('端末には保存しましたが、同期に失敗しました')}}
function showToast(message){status.textContent=message;setTimeout(()=>{if(status.textContent===message)status.textContent='待機中'},3500)}

function setAccountUI(){const logged=Boolean(session),configured=cloudConfigured();$('#account-button').textContent=logged?(session.user.email||'ログイン中'):'ログイン';$('#history-mode').textContent=logged?'スマホ・PC間で同期中':configured?'ログインすると端末間で同期できます':'現在はこの端末だけに保存されます';$('#support-state').textContent=logged?'送信できます':configured?'ログインが必要':'クラウド設定が必要';$('#support-state').classList.toggle('online',logged);$('#support-form').querySelector('button').disabled=!logged;$('#logout-button').hidden=!logged;$('#login-form').hidden=logged;$('#login-copy').textContent=logged?`${session.user.email} でログイン中です`:configured?'メールに届くログインリンクを開くだけ。パスワードは不要です。':'端末間同期を有効にするにはSupabaseの設定が必要です。'}
async function handleSession(next){session=next;setAccountUI();history=localHistory();if(session){try{await syncLocalMeetings(history);history=mergeHistory(await listCloudMeetings(),history);writeLocal(history);await refreshTickets();ticketTimer??=setInterval(refreshTickets,20000)}catch(e){console.error(e);showToast('クラウド同期の読み込みに失敗しました')}}else{if(ticketTimer){clearInterval(ticketTimer);ticketTimer=null}$('#ticket-list').innerHTML='';history=localHistory()}renderHistory()}

async function refreshTickets(){if(!session)return;try{const tickets=await listTickets(),box=$('#ticket-list');if(!tickets.length){box.innerHTML='<div class="feature-empty compact">お問い合わせ履歴はまだありません</div>';return}box.innerHTML=tickets.map(t=>`<article class="ticket"><div class="ticket-title"><div><small>#${esc(t.public_id)}・${new Date(t.created_at).toLocaleDateString('ja-JP')}</small><h3>${esc(t.subject)}</h3></div><span>${t.status==='closed'?'解決済み':'対応中'}</span></div><div class="messages">${t.ticket_messages.map(m=>`<div class="message ${m.sender==='admin'?'admin':'user'}"><b>${m.sender==='admin'?'Meeting Canvasからの返信':'あなた'}</b><p>${esc(m.body).replace(/\n/g,'<br>')}</p><time>${new Date(m.created_at).toLocaleString('ja-JP')}</time></div>`).join('')}</div><form class="ticket-reply" data-ticket="${t.id}"><input maxlength="1000" placeholder="追加メッセージを入力"/><button>送る</button></form></article>`).join('');box.querySelectorAll('.ticket-reply').forEach(form=>form.onsubmit=async e=>{e.preventDefault();const input=form.querySelector('input');if(!input.value.trim())return;form.querySelector('button').disabled=true;try{await replyToTicket(form.dataset.ticket,input.value.trim());input.value='';await refreshTickets()}finally{form.querySelector('button').disabled=false}})}catch(e){console.error(e);$('#support-feedback').textContent='お問い合わせ履歴を読み込めませんでした'}}

file.onchange=async()=>{if(!file.files[0])return;file.disabled=true;dot.classList.add('pulse');try{status.textContent='音声を準備中…';text.value=await transcribe(await decode(file.files[0]));status.textContent='完成しました';render();await saveCurrentHistory()}catch(e){console.error(e);status.textContent='処理できませんでした。MP3・M4A・WAVを試すか、文字起こしを貼り付けてください。'}finally{file.disabled=false;dot.classList.remove('pulse')}};
text.oninput=render;name.oninput=render;$('#sample').onclick=()=>{text.value=sample;render()};$('#save-history').onclick=saveCurrentHistory;
$('#account-button').onclick=()=>{$('#login-panel').hidden=false};$('#login-close').onclick=()=>{$('#login-panel').hidden=true};$('#login-panel').onclick=e=>{if(e.target.id==='login-panel')e.currentTarget.hidden=true};
$('#login-form').onsubmit=async e=>{e.preventDefault();const feedback=$('#login-feedback');feedback.textContent='送信中…';try{await sendMagicLink($('#login-email').value.trim());feedback.textContent='ログイン用メールを送りました。メール内のリンクを開いてください。'}catch(err){feedback.textContent=err.message||'送信できませんでした'}};
$('#logout-button').onclick=async()=>{await signOut();$('#login-panel').hidden=true};
$('#support-form').onsubmit=async e=>{e.preventDefault();const feedback=$('#support-feedback');if(!session){$('#login-panel').hidden=false;return}const button=e.currentTarget.querySelector('button');button.disabled=true;feedback.textContent='送信中…';try{await createTicket($('#support-subject').value.trim(),$('#support-message').value.trim());e.currentTarget.reset();feedback.textContent='お問い合わせを送信しました。Gmailからの返信もここに表示されます。';await refreshTickets()}catch(err){feedback.textContent=err.message||'送信できませんでした'}finally{button.disabled=false}};

history=localHistory();renderHistory();setAccountUI();
if(cloudConfigured()){try{await initCloud();onAuthChange(handleSession);await handleSession(await getSession())}catch(e){console.error(e);showToast('クラウド同期を開始できませんでした')}}
