import{CLOUD_CONFIG}from'./config.js';
let client=null;
export const cloudConfigured=()=>Boolean(CLOUD_CONFIG.supabaseUrl&&CLOUD_CONFIG.supabasePublishableKey);
export async function initCloud(){if(!cloudConfigured())return null;const{createClient}=await import('https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm');client=createClient(CLOUD_CONFIG.supabaseUrl,CLOUD_CONFIG.supabasePublishableKey,{auth:{persistSession:true,detectSessionInUrl:true}});return client}
export async function getSession(){if(!client)return null;return(await client.auth.getSession()).data.session}
export function onAuthChange(callback){return client?.auth.onAuthStateChange((_event,session)=>callback(session))}
export async function sendMagicLink(email){if(!client)throw new Error('クラウド同期が未設定です');const{error}=await client.auth.signInWithOtp({email,options:{emailRedirectTo:location.origin+location.pathname}});if(error)throw error}
export async function signOut(){if(client)await client.auth.signOut()}
export async function syncLocalMeetings(records){if(!client||!records.length)return;const session=await getSession();if(!session)return;const rows=records.map(r=>({user_id:session.user.id,client_id:r.id,title:r.title,transcript:r.transcript,minutes:r.minutes,created_at:r.created_at}));const{error}=await client.from('meeting_history').upsert(rows,{onConflict:'user_id,client_id',ignoreDuplicates:true});if(error)throw error}
export async function saveCloudMeeting(record){if(!client)return;const session=await getSession();if(!session)return;const{error}=await client.from('meeting_history').upsert({user_id:session.user.id,client_id:record.id,title:record.title,transcript:record.transcript,minutes:record.minutes,created_at:record.created_at},{onConflict:'user_id,client_id'});if(error)throw error}
export async function listCloudMeetings(){if(!client)return[];const{data,error}=await client.from('meeting_history').select('client_id,title,transcript,minutes,created_at').order('created_at',{ascending:false}).limit(50);if(error)throw error;return(data||[]).map(r=>({id:r.client_id,...r}))}
export async function createTicket(subject,body){if(!client)throw new Error('クラウド同期が未設定です');const session=await getSession();if(!session)throw new Error('ログインしてください');const{data:ticket,error}=await client.from('tickets').insert({user_id:session.user.id,user_email:session.user.email,subject}).select().single();if(error)throw error;const{error:messageError}=await client.from('ticket_messages').insert({ticket_id:ticket.id,sender:'user',body});if(messageError)throw messageError;return ticket}
export async function replyToTicket(ticketId,body){if(!client)throw new Error('クラウド同期が未設定です');const{error}=await client.from('ticket_messages').insert({ticket_id:ticketId,sender:'user',body});if(error)throw error}
export async function listTickets(){if(!client)return[];const{data,error}=await client.from('tickets').select('id,public_id,subject,status,created_at,ticket_messages(id,sender,body,created_at)').order('created_at',{ascending:false});if(error)throw error;return(data||[]).map(t=>({...t,ticket_messages:(t.ticket_messages||[]).sort((a,b)=>new Date(a.created_at)-new Date(b.created_at))}))}
